### PR TITLE
Stats graphs split

### PR DESCRIPTION
**Pull request by qasemsai**
Added graphs and fixed some statistics, modified other classes as necessary for graphs.

### CODE REVIEW

**Comment by mikegreber** [comment]
Looks good, but could you maybe change the layout to scroll? (maybe a ScrollView). Part of the time plot graph gets cut off when I open it in my emulator.

**Comment by qasemsai** [comment]
> Looks good, but could you maybe change the layout to scroll? (maybe a ScrollView). Part of the time plot graph gets cut off when I open it in my emulator.

Sure, will try to implement that layout in an update.

**Comment by archit-soni** [comment]
Scrollview implemented.

**Review by mikegreber — APPROVED** [review]
I just made one commit to move getFilteredTrials() into super class, looks good to merge to me.

**Pull request merged**
